<?php

namespace AppBundle\Repository;

/**
 * MobileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileRepository extends \Doctrine\ORM\EntityRepository
{
}
