<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Manufacturer;

/**
 * MobileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileRepository extends AbstractRepository
{
    public function search($term, Manufacturer $manufacturer = null, $order = 'asc', $limit = 20, $offset = 0)
    {
        $qb = $this
            ->createQueryBuilder('m')
            ->select('m')
            ->orderBy('m.name', $order)
        ;
        
        if ($term) {
            $qb
                ->where('m.name LIKE ?1')
                ->setParameter(1, '%'.$term.'%')
            ;
        }

        if ($manufacturer) {

        }
        
        return $this->paginate($qb, $limit, $offset);
    }
}