# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Application: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_APPLICATION: ROLE_APPLICATION
        ROLE_BILEMO: [ROLE_USER, ROLE_APPLICATION]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api_doc:
            pattern: ^/api/doc
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false

    access_control:
       - { path: ^/api/applications, roles: [ ROLE_BILEMO ] }
       - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY, ROLE_APPLICATION ] }